= Multi-Proxy with websocket asynchronous responses

This is a project that is a test example of a proxy service
that multiplexes incoming requests and distributes those
to multiple endpoints. It then responds back to the client
via a WebSocket, asynchronusly and immediately when responses
from the endpoints arrive. The project has 2 modules.

== link:websocket-service[websocket-service]
Provides a Multi-Proxy service that sends an incoming
request to multiple endpoints simultaneously, then provides
answers back to the client asynchronously on each response
from each endpoint respectively.

== link:simple-service[simple-service]
Provides a simple service (which can be reused
to simulate multiple endpoints that provides this service).

== Overview
image::doc/overview.svg[Overview]

== Run
To test this service, you can start the services in the modules (link:simple-service[simple-service] and link:websocket-service[websocket-service]) respectively via
[source,shell]
-----
mvn spring-boot:run
-----
Then navigate to http://localhost:8082 view the example client
webpage (this can be done in multiple web windows to simulate
more than one client simultaneously accessing the proxy)
